/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import models.Customer;
import models.Room;
import models.Service;

/**
 *
 * @author Quandeptrai
 */
public class RoomSignService extends javax.swing.JDialog {

    private MainFrame mainFrame;
    private DefaultTableModel serviceTableModel;
    private JTable serviceTable;
    private Room selectedRoom;

    /**
     * Creates new form SignService
     */
    public RoomSignService(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public RoomSignService(java.awt.Frame parent, boolean modal, JTable serviceTable, Room selectedRoom) {
        super(parent, modal);
        this.mainFrame = (MainFrame) parent;
        this.serviceTable = new JTable();
        this.serviceTable.setModel(serviceTable.getModel());
        this.serviceTableModel = (DefaultTableModel) serviceTable.getModel();
        this.selectedRoom = selectedRoom;
        initComponents();
        this.setTitle("Đăng ký dịch vụ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = serviceTable;
        confirmBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(serviceTable.getModel());
        jScrollPane1.setViewportView(jTable1);

        confirmBtn.setText("Xác Nhận");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Quay Lại");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(72, 72, 72)
                .addComponent(confirmBtn)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(confirmBtn))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        if (this.serviceTable.getSelectedRows().length > 1) {
            mainFrame.showMessage("Chọn tối đa một dịch vụ !");
            return;
        }
        int selectedRow = serviceTable.getSelectedRow();
        if (selectedRow == -1) {
            mainFrame.showMessage("Chưa Chọn Dịch Vụ Nào");
            return;
        }
        String name = serviceTableModel.getValueAt(selectedRow, 0).toString();
        Service service = mainFrame.findServiceByName(name);
        mainFrame.signService(selectedRoom, service);
        this.setVisible(false);
    }//GEN-LAST:event_confirmBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
