/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import java.util.Date;
import javax.swing.table.DefaultTableModel;
import models.Customer;
import models.Room;

/**
 *
 * @author Quandeptrai
 */
public class SignRoom extends javax.swing.JDialog {

    /**
     * Creates new form SignRoom
     */
    private MainFrame mainFrame;
    private DefaultTableModel customerTableModel;
    private javax.swing.JTable customerTable;
    private Room selectedRoom;
    private boolean isOrderRoom;

    public SignRoom(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public SignRoom(java.awt.Frame parent, boolean modal, javax.swing.JTable customerTable, Room selectedRoom, boolean isOrderRoom) {
        super(parent, modal);
        this.setLocationRelativeTo(null);
        this.mainFrame = (MainFrame) parent;
        this.customerTable = new javax.swing.JTable();
        this.customerTable.setModel(customerTable.getModel());
        this.customerTableModel = (DefaultTableModel) customerTable.getModel();
        this.selectedRoom = selectedRoom;
        this.isOrderRoom = isOrderRoom;
        initComponents();
        this.setTitle("Đăng ký thuê phòng");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new Button();
        sign = new Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = customerTable;

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        back.setText("Quay lại");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        sign.setText("Xác Nhận");
        sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signActionPerformed(evt);
            }
        });

        jTable1.setModel(customerTable.getModel());
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(59, 59, 59)
                .addComponent(sign)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sign)
                    .addComponent(back))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }// GEN-LAST:event_backActionPerformed

    private void signActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_signActionPerformed
        if (this.customerTable.getSelectedRows().length > 1) {
            mainFrame.showMessage("Chỉ được chọn một khách hàng");
            return;
        }
        int selectedRow = customerTable.getSelectedRow();
        if (selectedRow == -1) {
            mainFrame.showMessage("Vui lòng chọn một khách hàng");
            return;
        }

        String id = customerTableModel.getValueAt(selectedRow, 0).toString();
        Customer customer = mainFrame.findCustomerById(id);
        Date rentDate = null;
        if (isOrderRoom) {
            rentDate = customer.getRentDate();
            if (rentDate != null && rentDate.compareTo(new Date()) > 0) {
                mainFrame.orderRoom(selectedRoom, customer, rentDate);
            } else {
                mainFrame.showMessage("Ngày Đặt Trước Không Hợp Lệ");
            }
        } else {
            rentDate = new Date();
            mainFrame.signRoom(selectedRoom, customer, rentDate);
        }

        this.setVisible(false);
    }// GEN-LAST:event_signActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton sign;
    // End of variables declaration//GEN-END:variables
}
